/// Flutter icons GreenspaceIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GreenspaceIcons
///      fonts:
///       - asset: fonts/GreenspaceIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GreenspaceIcons {
  GreenspaceIcons._();

  static const _kFontFam = 'GreenspaceIcons';

  static const IconData flower_tulip = const IconData(0xe800, fontFamily: _kFontFam);
}
